name: Commandes Shell

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run : echo "Hello Kitten"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: commandes python
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows:
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run:  Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash